from typing import KeysView
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
import time

print("======= E-MAIL =======")
e = str(input('ESCOLHA O DESTINATARIO: \n1 - Nome01 \n2 - Nome02 \n3 - Nome03 \n => '))
if e =='1':
    d = str('teste.01@hotmail.com')
if e =='2':
    d = str('teste.02@hotmail.com.com')
if e =='3':
    d = str('teste.03@hotmail.com')
t = input('DIGITE O TITULO: \n => ')
print("==="*9)
a = input('DIGITE O TEXTO: \n => ')
print("==="*9)
print("Enviando e-mail...")
print("==="*9)
time.sleep(2)
navegador = webdriver.Chrome()
navegador.get("https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1657823452&rver=7.0.6737.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f%3fnlp%3d1%26RpsCsrfState%3d9d1749af-16f7-1a8e-78fe-2f5d2f6212e8&id=292841&aadredir=1&CBCXT=out&lw=1&fl=dob%2cflname%2cwld&cobrandid=90015")
time.sleep(1)
navegador.find_element("xpath", '/html/body/div/form[1]/div/div/div[2]/div[1]/div/div/div/div/div[1]/div[3]/div/div/div/div[2]/div[2]/div/input[1]').send_keys("email@hotmail.com")
navegador.find_element("xpath", '//*[@id="idSIButton9"]').click()
time.sleep(1)
navegador.find_element("xpath", '//*[@id="i0118"]').send_keys('senha')
navegador.find_element("xpath", '//*[@id="idSIButton9"]').click()
time.sleep(1)
navegador.find_element("xpath", '//*[@id="idBtn_Back"]').click()
time.sleep(4)
navegador.find_element("xpath", '//*[@id="app"]/div/div[2]/div[2]/div[1]/div/div/div/div/div/div[1]/div[2]/div/div/button/span').click()
time.sleep(2)
navegador.find_element("xpath", '//*[@id="docking_InitVisiblePart_0"]/div[1]/div[1]/div[1]/div/div[3]/div/div/div[1]').send_keys(d)
time.sleep(1)
navegador.find_element("xpath", '//*[@id="FloatingSuggestionsItemId-0"]/div/button[1]/span/div/div').click()
time.sleep(1)
navegador.find_element("xpath", '//*[@id="TextField148"]').send_keys(t)
time.sleep(1)
navegador.find_element("xpath", '//*[@id="editorParent_1"]/div').send_keys(a)
time.sleep(1)
navegador.find_element("xpath", '//*[@id="app"]/div/div[2]/div[2]/div[1]/div/span/div/div/div/div/div[1]/div[2]/button').click()
navegador.find_element("xpath", '//*[@id="MainModule"]/div/div/div[1]/div/div/div[1]/div/div[3]/div[4]/div').click()
time.sleep(3)
navegador.close()
time.sleep(3)
print("==="*9)
print("E-MAIL ENVIADO!")
print("==="*9)
